# Generated by Django 6.0.3 on 2026-04-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('curso', models.CharField(max_length=150)),
                ('periodo', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('git', models.URLField()),
                ('linked', models.URLField()),
                ('imagem_url', models.URLField(help_text='URL de uma imagem para o perfil')),
            ],
        ),
    ]
