# Generated by Django 6.0.3 on 2026-04-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Pessoal', 'Pessoal'), ('Disciplina', 'Disciplina')], max_length=20)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('git', models.URLField()),
            ],
        ),
    ]
